# Generated by Django 5.0.6 on 2024-05-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitem_created_at_todoitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
