# Generated by Django 5.0.6 on 2024-05-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todoitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
